tiles_opq_table DW OFFSET grass_opq_0 ; ID 0
    DW OFFSET rock_opq_0              ; ID 1

; TODO: Review orders
tiles_trns_table DW 0                 ; ID 0
    DW OFFSET flower_trns_0           ; ID 1
    DW OFFSET plant_trns_0            ; ID 2
    DW OFFSET plant_trns_1            ; ID 3
    DW OFFSET plant_trns_2            ; ID 4
    DW OFFSET rock_trns_0             ; ID 5
    DW OFFSET rock_trns_1             ; ID 6
    DW OFFSET tresors_trns_0          ; ID 7
