; IDs must follow the definition here: defs/gfx/tiles.inc

tiles_table DW 10 DUP(0)            ; Place holder

  DW OFFSET grass_opq_0             ; ID 10

  DW 9 DUP(0)                       ; Place holder

  DW OFFSET flower_trns_0           ; ID 20
  DW OFFSET flower_trns_1           ; ID 21

  DW 8 DUP(0)                       ; Place holder

  DW OFFSET plant_trns_0            ; ID 30
  DW OFFSET plant_trns_1            ; ID 31
  DW OFFSET plant_trns_2            ; ID 32

  DW 7 DUP(0)                       ; Place holder

  DW OFFSET rock_opq_0              ; ID 40
  DW OFFSET rock_trns_0             ; ID 41
  DW OFFSET rock_trns_1             ; ID 42

  DW 7 DUP(0)                       ; Place holder

  DW OFFSET tresors_trns_0          ; ID 50
