TILE_WIDTH  EQU 16
TILE_HEIGHT EQU 16
TILE_COLS   EQU 20
TILE_ROWS   EQU 12

; --- Tiles IDs ---
VOID_0      EQU 0     ; Empty
GRS_O0      EQU 10    ; Grass 0

FLO_T0      EQU 20    ; Flower 0
FLO_T1      EQU 21    ; Flower 1
FLO_T2      EQU 22    ; Flower 2
FLO_T3      EQU 23    ; Flower 3

PLT_T0      EQU 30    ; Plant 0
PLT_T1      EQU 31    ; Plant 1
PLT_T2      EQU 32    ; Plant 2
PLT_T3      EQU 33    ; Plant 3
PLT_T4      EQU 34    ; Plant 4

RKS_T0      EQU 40    ; Rock 0
RKS_T1      EQU 41    ; Rock 1
RKS_T2      EQU 42    ; Rock 2

TRS_T0      EQU 50    ; Treasure 0
