TILE_WIDTH  EQU 16
TILE_HEIGHT EQU 16
TILE_COLS   EQU 20
TILE_ROWS   EQU 12

; --- Tiles IDs ---
VOID_0      EQU 0     ; Empty
GRS_O0      EQU 10    ; Grass 0

FLO_T0      EQU 20    ; Flower 0
FLO_T1      EQU 21    ; Flower 1

PLT_T0      EQU 30    ; Plant 0
PLT_T1      EQU 31    ; Plant 1
PLT_T2      EQU 32    ; Plant 2

RKS_O0      EQU 40    ; Rock 0
RKS_T0      EQU 41    ; Rock 1
RKS_T1      EQU 42    ; Rock 2

TRS_T1      EQU 50    ; Treasure 1
